### ISSUE TITLE
The /heroes endpoint doesn't seem to be giving me correct values. I've tried it with a few different users and it didn't work right with any. Is there some date issue? Because I queried it for an old account that I haven't used since March and got 0 games played for all heroes.

### ISSUE THREAD

**Issue by AnujDutt2701** [odota/docs#13]

**Comment by howardchung** [comment]
Example link?

**Comment by AnujDutt2701** [comment]
https://api.opendota.com/api/players/69804661/heroes

**Comment by howardchung** [comment]
It looks like this account doesn't have Expose Public Match Data turned on.  This is required in order to not show up anonymously in matches.  Once that's done, you can use the "refresh" button on the player profile to request old matches.
