### ISSUE TITLE
Hi. The endpoint below has some issue with the game mode that is returned. I never play ranked but according to the results the game mode returned = 22. https://api.opendota.com/api/players/420567290/matches?limit=20 

### ISSUE THREAD

**Issue by AnujDutt2701** [odota/docs#14]

**Comment by howardchung** [comment]
Unranked all pick is now also game mode 22 (all draft).  You need to use lobby_type to distinguish ranked from unranked.

**Comment by AnujDutt2701** [comment]
https://github.com/odota/dotaconstants/blob/master/json/game_mode.json could this please be updated then? Or am i supposed to refer to something else?

**Comment by howardchung** [comment]
Thanks I've updated it.  Those strings are just used as a reminder.  The actual display strings on OpenDota.com are in the odota/ui repo.
