### ISSUE TITLE
/Teams endpoint doesn't return team logo. If this could be added it will be a big help as querying steam API for just the team logo is a very tedious process.

### ISSUE THREAD

**Issue by AnujDutt2701** [odota/docs#15]

**Comment by howardchung** [comment]
If the logos are static and you can make a list of them, we can add those to the API.  However currently we don't store this data

**Comment by AnujDutt2701** [comment]
Hi. Sorry for the late response. I've compiled some data. You can parse through this and store team logos.
[teams_json_data.zip](https://github.com/odota/docs/files/1167375/teams_json_data.zip)

**Comment by howardchung** [comment]
I opened https://github.com/odota/core/issues/1506 to track this
