### ISSUE TITLE
Definition of array doesn't match specification

### ISSUE THREAD

**Issue by Seraphli** [odota/docs#16]
On the swagger specification page https://swagger.io/specification/, they say item field is required if type is array. 
![image](https://user-images.githubusercontent.com/1586755/28406849-9dd6f72e-6d64-11e7-814a-0a1631071b20.png)
But in your api, there are several places which don't match this specification.
![image](https://user-images.githubusercontent.com/1586755/28406879-b69821ca-6d64-11e7-99ac-dc411e9ba65f.png)
This will cause problems while using swagger to generate code.

**Comment by howardchung** [comment]
Thanks.  Yeah, we should fix this by defining the array object structure.

**Comment by howardchung** [comment]
Code is in:
https://github.com/odota/core/blob/master/routes/spec.js

Any field that has `type: 'array'` should have items defined.

**Comment by Seraphli** [comment]
Should I wait for an update of api?

**Comment by howardchung** [comment]
Depends on how urgently you need the fix.  I can make the fix when I have some time, but don't know exactly when that will be.  If you know how to fix it and can submit a PR that would be great

**Comment by Seraphli** [comment]
If I want to fix this, I need to have some response examples. For example, `buyback_log` in the `player`. Is there any real response example?

**Comment by Seraphli** [comment]
I was trying to edit api using an response of my own match. I found out the `buyback_log` is `null`, although there were two players who bought back in this game. Also the value of `dn_t` and `gold_t` are `null` too. 
And I was trying to use the editor provided by swagger, which popped up these error. 
![image](https://user-images.githubusercontent.com/1586755/28420686-82067da4-6d95-11e7-8aee-9eb7342cb80e.png)
I tried to add `"items":{"type": "number"}` after all missing `item` arrays, but the error still existed. I don't know how to fix this.

**Comment by howardchung** [comment]
Sample response:
https://api.opendota.com/api/matches/3170212000

Fields may be null if they rely on replay parsing and the replay hasn't been parsed et.

**Comment by Seraphli** [comment]
1. Values are separated by commas, not ended with commas. In the code https://github.com/odota/core/blob/master/routes/spec.js, there are a lot of places which commas are placed behind the final item.
2. In the response, `kill_log` don't have a `type` field.
3. Type definition error. `match_id` and `acccount_id` should be defined as `integer`, not `number`. Because `number` represent `float` or `double`, while `integer` represent `int32` or `int64`.
4. `obs_left_log` and `obs_log` in the response are empty array. I will just assume the type of these items are `object`.
5. `permanent_buffs` is `null`. So I change the `type` to `object`. Because if it is `array`, it should return `[]`(empty array).
6. `runes` has a strange definition. I don't really get it.

**Comment by Seraphli** [comment]
https://github.com/Seraphli/core/commit/d4bfb938fbd84c54abd2251d44231ccfadf1ea55
Here is my fix.

**Comment by howardchung** [comment]
Can you submit a pull request?

Comments:
* Lint rules are to place commas after all elements in the code.  When converted to JSON these commas disappear.
* Not sure if permanent buffs should be an object.  It's either an array or null, but will never be `{}`.
* The keys in the runes object are the rune ID and the value is the count of that rune picked up.

**Comment by Seraphli** [comment]
OK, I will submit a pull request. I just thought you should check it before the submission. And I set the runes to dictionary type, string to string mapping.

**Comment by howardchung** [comment]
Typically I do code review on the pull request
